#!/bin/sh

# This fetch never lies, so you should always trust it.
# No need to edit this file unless yuore STUPID and want it to break.

white=$(printf '\033[37m')
bold=$(printf '\033[1m')
reset=$(printf '\033[0m')

purple=$(printf '\033[35m')
blue=$(printf '\033[34m')
cyan=$(printf '\033[36m')
green=$(printf '\033[32m')
yellow=$(printf '\033[33m')
orange=$(printf '\033[38;5;208m')
red=$(printf '\033[31m')

logo1="      .--.     "
logo2="     |o_o |    "
logo3="     |:_/ |    "
logo4="    //   \\ \\   "
logo5="   (J     l )  "
logo6="  /'\_   _/'\\  "
logo7="  \___)=(___/  "

distro=$( cat /etc/os-release | grep PRETTY_NAME | tr -d "'" | cut -d '=' -f2 )
wm="something niche probably"
hostname=$(cat /proc/sys/kernel/hostname)
space="               "
cpu=$( cat /proc/cpuinfo | grep -m 1 'model name' | cut -d':' -f 2 )

packages=$(
	if command -v apt > /dev/null 2>&1; then
	   apt list --installed | wc -l
	elif command -v dnf > /dev/null 2>&1; then
	   dnf list installed | wc -l
	elif command -v zypper > /dev/null 2>&1; then
	   zypper search -i | wc -l
	elif command -v pacman > /dev/null 2>&1; then
	   pacman -Qq | wc -l
	elif command -v xbps-query > /dev/null 2>&1; then
		xbps-query -l | wc -l
	elif command -v emerge > /dev/null 2>&1; then
		equery list '*' | wc -l
	else
	   echo "fuckahh why would i know"
	fi
)
packages_low=$(( $packages * 10 / 12 ))
packages_high=$(( $packages * 16 / 10 ))

uptime_seconds=$( cut -d' ' -f 1 /proc/uptime | cut -d'.' -f 1 )
uptime_minutes=$(( $uptime_seconds / 60 ))
uptime_hours=$(( $uptime_minutes / 60 ))
uptime=$(
	if [ "$uptime_hours" -ge 10 ]; then
		echo "${green}${bold}ew get off your computer wtf.${reset} Youve been on for ${uptime_hours} h"
	elif [ "$uptime_hours" -ge 5 ]; then
		echo "${green}${bold}go touch some grass, ok?${reset} ${uptime_hours} h"
	elif [ "$uptime_hours" -ge 1 ]; then
		echo "${green}${bold}keep on using that computer, computer boy.${reset} ${uptime_minutes} min"
	elif [ "$uptime_minutes" -ge 30 ]; then
		echo "${green}${bold}wow, not too much, huh?${reset} ${uptime_minutes} min"
	else 
		echo "${green}${bold}computah, make this guy super gay, horny, and addicted to their pc.${reset} ${uptime_minutes} min"
	fi
)

terminal=$(
	if [ $TERM = foot ]; then
			echo "${purple}${bold}ew you like feet? wtf. term${reset} = ew im not saying that" 
		elif [ $TERM = kitty ]; then
			echo "${purple}${bold}oh i love cats too! term${reset} = cat"
		elif [ $TERM = urxvt ]; then
			echo "${purple}${bold}the best x11 term btw. term${reset} = " $TERM
		else 
			echo "${purple}${bold}term${reset} =" $TERM
	fi	
)

ram=$( grep MemTotal /proc/meminfo | tr -s ' ' | cut -d' ' -f 2 )
ram_B=$(( $ram * 1000 ))
ram_GB=$(( $ram / 1000000 ))
ram_conclusion=$(
	if [ $ram_GB -ge 63 ]; then
			echo $ram_B "Bytes??? Holy shit are you a datacenter?"
		elif [ $ram_GB -ge 31 ]; then
			echo $ram_B "Bytes.. damn thats quite a bit man.. leave the windows(11) open"
		elif [ $ram_GB -ge 15 ]; then
			echo $ram_B "Bytes, meh pretty average"
		elif [ $ram_GB -ge 7 ]; then
			echo $ram_B "Bytes, you better hope GTA6 never releases"
		else
			echo $ram_B "Bytes only..? We all think you deserve some more man"
	fi
)


echo "  sudo apt ddos" ${green}${bold}$USER${reset}'@'${green}${bold}$hostname${reset}

echo "$logo1" "${red}${bold}shitty distro btw${reset} = " $distro

echo "$logo2" "${orange}${bold}a.. colonel sanders? what? idk${reset} = $(uname -r)"

# how do i do this one 
echo "$logo3" "${yellow}${bold}managing windows 11${reset} = " $wm

echo "$logo4" $uptime

echo "$logo5" "${cyan}${bold}aliexpress packages${reset} = prolly like" $packages_low 'to' $packages_high

echo "$logo6" "${blue}${bold}like.. a seashell?${reset} = " $SHELL

echo "$logo7" $terminal

echo ''

echo "  well ${cyan}specs${reset}.. I suppose ik what those are"

echo "$space" "${yellow}cpu${reset} =" $cpu

echo "$space" "${blue}ai food${reset} =" $ram_conclusion

# havent figured out how to do this yet
echo "$space" "${purple}gpu${reset} = you dont have one you poor bastard"

# Ik its badly made btw
